application: android-issuetrackerredirect
version: 1
runtime: python
api_version: 1
default_expiration: 7d

handlers:
- url: /(robots.txt)
  static_files: static/\1
  upload: static/robots.txt

- url: /(application_version)
  static_files: static/\1
  mime_type: text/plain
  expiration: 1s
  upload: static/application_version

- url: .*
  script: redirect.py
